chanzuckerberg/miniwdl

- README.md
@mckinsel @bkmartinjr Please look this over before we put onto the front page. Do we need to add any pro forma notices etc.?
The package is not actually live in PyPI yet, but you can try it from the test server if you'd like:
```
pip3 install lark-parser==0.6.4
pip3 install --index-url https://test.pypi.org/simple/ miniwdl
```
> first cut at readme content

- README.md
- WDL/Env.py
- WDL/Expr.py
- WDL/Tree.py
- WDL/Type.py
- WDL/Value.py
- WDL/__init__.py
- docs/conf.py
- docs/index.rst
- readthedocs.yml
- requirements.dev.txt
> Documentation pass

- WDL/CLI.py
- WDL/Lint.py
- tests/test_3corpi.py
- decorator for Linter subclasses to self-register
- overhaul corpi test harness to test the number of lint warnings generated from each class
> linting infra improvement

- WDL/Expr.py
- WDL/StdLib.py
- tests/test_2calls.py
- tests/test_3corpi.py
we can ignore that x is optional when typechecking EXPR_WITH_x
> special typechecking for if defined(x) then EXPR_WITH_x else SOME_DEFAULT

- Dockerfile
- Makefile
- README.md
- WDL/CLI.py
- WDL/Env.py
- tests/check.t
- tests/cromwell.t
- tests/test_0eval.py
`miniwdl cromwell` provides a nicer CLI for testing a workflow locally (by running it through Cromwell)
> miniwdl cromwell MVP

- WDL/CLI.py
- WDL/Lint.py
- WDL/Type.py
- test_corpi/contrived/check_quant.wdl
- test_corpi/contrived/contrived.wdl
- tests/test_2calls.py
- tests/test_4corpi.py
> tighten array coercions

- WDL/Error.py
- WDL/_parser.py
- test_corpi/contrived/issue120.wdl
- tests/test_1doc.py
> Change internal repr of meta and parameter_meta values from [interpolated] string to string_literal

- WDL/Tree.py
- WDL/Type.py
- tests/test_1doc.py
refactors detection of circular struct typedefs
> properly resolve struct types nested within compound-type members of other structs

- Makefile
- WDL/CLI.py
- tests/cromwell.t
- tests/runner.t
A lot of the runner CLI mechanics are shared between `miniwdl cromwell` and the new `miniwdl run`.
> CLI for (alpha) task runtime

- WDL/Tree.py
- WDL/runtime/task.py
- tests/test_1doc.py
Workflow cycle detection logic had been looking at the graph of declarations & calls only.
> detect cycles involving scatter & conditional expressions

- WDL/Tree.py
- WDL/Walker.py
- tests/test_1doc.py
Helps with dependency bookkeeping whilst executing scatters.
Add Gather nodes to Scatter.children & Walker
> add WorkflowNode.scatter_depth

- .coveragerc
- .travis.yml
- Makefile
- WDL/runtime/workflow.py
- requirements.dev.txt
- tests/test_3corpi.py
- tests/test_4taskrun.py
This enables parallelization of the unit test suite, which is a boon since it has grown to take 10+ minutes running serially.
> upgrade to pytest

- WDL/CLI.py
- tests/cromwell.t
> run/cromwell CLI: support relative paths in input JSON file

- WDL/_parser.py
- tests/test_1doc.py
do the best we can with it using our most up-to-date grammar rules
> parser: recognize 'version development'

- .travis.yml
- WDL/runtime/task.py
- tests/test_4taskrun.py
Seems we need to do this ourselves in certain configurations (issue #232)
> add default ":latest" tag to docker image if none present

- .travis.yml
- Makefile
> split CI into multiple travis jobs

- WDL/CLI.py
- WDL/runtime/task.py
- WDL/runtime/workflow.py
- tests/test_4taskrun.py
Accept JSON giving default values to apply in all task runtime sections
> miniwdl run --runtime-defaults

- WDL/Expr.py
- WDL/Value.py
- tests/test_0eval.py
- tests/test_1doc.py
factor out unification logic shared with Array & IfThenElse
> improve Map type unification

- WDL/CLI.py
- WDL/Tree.py
- WDL/__init__.py
- WDL/_parser.py
- WDL/_util.py
- tests/runner.t
- tests/test_3corpi.py
> copy original WDL source text into run directory

- WDL/CLI.py
- WDL/runtime/__init__.py
- WDL/runtime/error.py
- WDL/runtime/task.py
- WDL/runtime/workflow.py
- tests/runner.t
> overhaul error propagation & logging

- WDL/_util.py
- WDL/runtime/cache.py
- WDL/runtime/download.py
- WDL/runtime/task.py
- WDL/runtime/workflow.py
- tests/test_4taskrun.py
Prepares for flocking all input files
[ ] include logic for not re-flocking the same file
> factor flock() logic out of CallCache

- WDL/Expr.py
- WDL/StdLib.py
- WDL/Type.py
- WDL/Value.py
- tests/test_0eval.py
- tests/test_5stdlib.py
> read_json() inference of nested types

- WDL/StdLib.py
- tests/test_5stdlib.py
https://github.com/openwdl/wdl/pull/362
Followed [Adding WDL functions](https://miniwdl.readthedocs.io/en/latest/add_functions.html) tutorial.
> Added suffix, quote and squote stdlib functions and tests

- WDL/StdLib.py
- WDL/Tree.py
- WDL/Value.py
- WDL/runtime/workflow.py
- tests/test_5stdlib.py
> [WDL 2.0] keys() and misc adjustments

- WDL/runtime/cache.py
- tests/test_8cache.py
> CallCache coherence for Directory inputs/outputs

- WDL/runtime/task_container.py
- stubs/docker/__init__.py
- tests/test_4taskrun.py
Ensures the exact image is logged and used consistently across a multi-node swarm
> docker: resolve image tag to RepoDigest before service creation

- docs/FAQ.md
- docs/getting_started.md
- docs/index.rst
@llangit-czi  FYI- just pulling your changes from mlin/miniwdl back into chanzuckerberg/miniwdl to keep them on the "trunk"
> upstreaming docs improvements

- WDL/runtime/__init__.py
- WDL/runtime/workflow.py
- tests/runner.t
https://bugs.python.org/issue41567
> work around python3.9 module import race condition

- WDL/Type.py
- WDL/Value.py
- tests/test_5stdlib.py
> allow Object type coercion to Map

- WDL/runtime/backend/docker_swarm.py
> Run the command in docker as if it had been directly invoked by login

- WDL/runtime/backend/docker_swarm.py
- WDL/runtime/backend/podman.py
- WDL/runtime/config_templates/default.cfg
- docs/runner_backends.md
> podman: configurable exe for rootless use

- WDL/runtime/backend/cli_subprocess.py
- WDL/runtime/backend/docker_swarm.py
- WDL/runtime/config_templates/default.cfg
- WDL/runtime/task_container.py
> add [task_runtime] command_shell to configure the shell

- WDL/runtime/task.py
> log warning for task input files with colliding basenames

- WDL/Value.py
- WDL/__init__.py
> fix incorrect array types returned from Value.from_json

- WDL/runtime/task.py
- tests/test_6workflowrun.py
> fix glob() in outputs from retried task

- .github/workflows/CI.yml
- WDL/Expr.py
- WDL/Value.py
- WDL/_parser.py
- tests/runner.t
> ensure optional fields in structs initialized from JSON

- WDL/runtime/cache.py
- tests/test_8cache.py
> fix cache of task with empty outputs

- tests/runner.t
- tests/test_7runner.py
> regression tests for issue #700

- WDL/Expr.py
- tests/test_7runner.py
> Array and IfThenElse type inference: allow an item/branch type to be Any and pass through

- WDL/_grammar.py
- tests/test_1doc.py
> allow trailing commas in meta arrays

- WDL/StdLib.py
- WDL/_util.py
- tests/test_5stdlib.py
> round half up

- WDL/_grammar.py
- WDL/_grammar_old.py
> reorganize lark grammars
