WDL/Error.py
WDL/Expr.py
WDL/StdLib.py
WDL/Type.py
WDL/Value.py
WDL/__init__.py
WDL/_parser.py
tests/test_HCAskylab.py
tests/test_doc.py
tests/test_eval.py

* Adding Map, Pair, and several stdlib stubs allows us to parse & typecheck all HCA/skylab workflows :champagne: 
* Grammatical ambiguity of ".left" and ".right" pair accessor operators leads to two separate code paths for handling them, depending on whether the left-hand side is an identifier or some other expression. It would be nice to eliminate this bifurcation in the future by ensuring "left" and "right" can't parse as an identifier part.
* Still TODO: map and pair literals, and unit tests thereof

Maps and Pairs

---

.travis.yml
Makefile
README.md
WDL/CLI.py
WDL/Env.py
WDL/Error.py
WDL/Expr.py
WDL/Lint.py
WDL/StdLib.py
WDL/Tree.py
WDL/Type.py
WDL/Value.py
WDL/Walker.py
WDL/__init__.py
WDL/_parser.py
requirements.dev.txt

YUGE diff introducing autopep8 and pylint to our CI, and cleaning up fuzz discovered in the process. Current pylint score 9.37/10
- `make` / `make test` includes pylint in "errors only" mode
- `make pretty` reformats code with autopep8, and displays pylint report
- Travis build fails if source code isn't at a fixed point for autopep8 (revision pinned in `requirements.dev.txt`)

pylint & autopep8

---

.pyre_configuration
Makefile
WDL/Env.py
WDL/Expr.py
WDL/Lint.py
WDL/Tree.py
WDL/Walker.py
tests/test_3corpi.py

Links each Expr.Ident to the Decl or Call it references, which is added during document typechecking by threading it through the type environment (as 'context').
This link makes it easy to ask whether the Expr.Ident lexically precedes the Decl/Call. It will also facilitate detection of cyclic dependencies and unused declarations.

ForwardReference linter

---

WDL/CLI.py
WDL/Expr.py
WDL/Lint.py
WDL/Tree.py
WDL/Walker.py
WDL/__init__.py
WDL/_parser.py
tests/test_1doc.py
tests/test_3corpi.py

**UnusedDeclaration:** a (non-output) value is declared, but not subsequently used in the task/workflow.
**UnusedCall:** the outputs of a call within a workflow are neither outputs from the workflow, nor used by anything else in the workflow.
In the process of developing these, we realized that the task commands in many draft-2 WDLs were not being parsed as expected (specifically, `${ }` delimited placeholders were ignored within `<<< >>>` delimited commands, which are indeed not recognized as placeholders in WDL 1.0). To address this, we introduce a rudimentary way to serve different grammar versions, and detect the version from the document header, if any. The mechanism will need more polishing.
Typecheck task runtime section.
Fix several bugs and omissions in the AST, Walker, etc.

UnusedDeclaration and UnusedCall linters

---

.gitmodules
WDL/Lint.py
WDL/StdLib.py
WDL/Tree.py
WDL/_parser.py
tests/test_1doc.py
tests/test_3corpi.py

Handle the deprecated, pre-1.0 style of specifying workflow outputs with just a namespaced identifier (referring to a call output) instead of a full declaration, or with a wildcard denoting all outputs from a call. We handle these with an AST rewrite into modern-style declarations during typechecking. The new productions exist only in the pre-1.0 version of the grammar.
Accepts a few previously blacklisted workflows and gatk4-cnn-variant-filter in the test corpi
Checks for duplicate output names

recognize deprecated workflow outputs syntax with identifiers and wildcards

---

WDL/Expr.py
WDL/Lint.py
WDL/Type.py
test_corpi/contrived/check_quant.wdl
test_corpi/contrived/contrived.wdl
tests/test_2calls.py
tests/test_3corpi.py

e.g. Array[Array[Int]] = [[:Int?:]]
Entailed pushing check_quant logic from Expr down into Type, and consolidating OptionalCoercion and NonemptyArrayCoercion linters into QuantityCoercion.

typecheck quantifiers in composite types

---

WDL/CLI.py
WDL/Error.py
WDL/Tree.py
WDL/__init__.py
WDL/_parser.py
test_corpi/contrived/incomplete.wdl
test_corpi/contrived/incomplete_call.wdl
test_corpi/contrived/incomplete_import.wdl
tests/cli.t
tests/test_2calls.py
tests/test_3corpi.py

Also, documents containing workflows with incomplete calls can be imported, so long as their workflow is not actually called.

Rudimentary URI import

---

WDL/CLI.py
WDL/Expr.py
WDL/Lint.py
WDL/StdLib.py
WDL/Type.py
test_corpi/contrived/check_quant.wdl
test_corpi/contrived/contrived.wdl
test_corpi/contrived/empty.wdl
tests/test_0eval.py
tests/test_2calls.py
tests/test_3corpi.py

read_json() can return values of different types depending on what's in the JSON file at runtime. Introduce WDL.Type.Any to model this, and use it instead of None to represent the item types of empty Array/Map literals.

read_json() stub and Any type

---

Dockerfile
WDL/CLI.py
WDL/Lint.py
WDL/_parser.py
tests/cli.t
tests/test_1doc.py
tests/test_3corpi.py

Uses ShellCheck on task commands and propagates any warnings it finds.
Subtleties/hacks:
- dummy values put in for expression placeholders in the task commands
- suppress several specific warnings that may be triggered by dummy values
- line/column numbers offset to correspond to original WDL source

shellcheck task commands

---

WDL/Env.py
WDL/Tree.py
tests/test_0eval.py
tests/test_1doc.py

- bind() can insert namespaces recursively as needed (deprecates namespace())
- bind() arguments reordered for consistency
- add unbind() and subtract()
- unit tests

refactor Env.bind

---

WDL/Env.py
WDL/Expr.py
WDL/Tree.py
test_corpi/contrived/tricky_outputs.wdl
tests/test_2calls.py

- Make them Env.Types instead of Env.Decls
- Correctly type the outputs of calls inside scatter and conditional sections
- Clean up internals using new Env.map

Rework effective_outputs

---

WDL/Lint.py
test_corpi/contrived/contrived.wdl
tests/test_4corpi.py

* detect coercions implied within compound types
* flag most File-to-String coercions at the workflow (but not task) level

Refine StringCoercion and FileCoercion linters

---

Makefile

This is used in the check target. It defaults to the previous value of
`$(HOME)/.local`, but can be set from the command line as follows:
```
PYTHON_ENV=<PATH TO DIRECTORY CONTAINING PYTHON ENVIRONMENT> make
{check|test}
```
Fixes https://github.com/chanzuckerberg/miniwdl/issues/102

Added PYTHON_ENV variable to Makefile

---

WDL/Expr.py
WDL/Lint.py
WDL/StdLib.py
WDL/Tree.py

Refactor StdLib (#14) in anticipation of needing to provide context-dependent typechecking/implementation logic for various functions. For example, numerous functions are tightly intertwined with the task execution environment and in some cases don't even make sense elsewhere (e.g. `stdout()`).

StdLib overhaul

---

WDL/CLI.py

@mlin - pkg_resources is (I believe) the standard way to handle versioning. This
can get a bit weird if git repo is missing, but usually if you're pip
installing with standard packaging PBR handles this just fine! Yay! :D
```
›› pipenv run pip install -e .
Obtaining file:///Users/jtratner/miniwdl
Requirement already satisfied: lark-parser==0.7.0 in /Users/jtratner/.virtualenvs/miniwdl-PSNaoBg-/lib/python3.6/site-packages (from miniwdl==0.1.7.dev2) (0.7.0)
Installing collected packages: miniwdl
Found existing installation: miniwdl 0.1.7.dev2
Uninstalling miniwdl-0.1.7.dev2:
Successfully uninstalled miniwdl-0.1.7.dev2
Running setup.py develop for miniwdl
Successfully installed miniwdl
›› pipenv run miniwdl --version
miniwdl 0.1.7.dev2
Cromwell-Version: 40
```

Simpler version handling

---

WDL/Tree.py
tests/test_1doc.py

exclude output declarations from Workflow.available_inputs

---

.travis.yml
Dockerfile
Makefile
WDL/Lint.py
WDL/Value.py
WDL/__init__.py
WDL/_util.py
WDL/runtime/__init__.py
WDL/runtime/task.py
requirements.txt
stubs/docker/__init__.py
tests/test_0eval.py
tests/test_5taskrun.py

Initial skeleton of the local task runtime, with proofs of concept for docker container management, file path mapping, and I/O stdlib functions like `stdout()` and `write_lines()`.

task runtime skeleton

---

WDL/CLI.py
WDL/Tree.py
WDL/__init__.py
WDL/_parser.py
tests/test_0eval.py
tests/test_5taskrun.py

These provide conversion between WDL.Env.Values and Cromwell-style JSON for inputs & outputs.
Subsumes simpler version used for miniwdl cromwell CLI.
Simplifies task runtime test cases

Add WDL.values_from_json, WDL.values_to_json

---

.gitmodules
WDL/Lint.py
WDL/Tree.py
WDL/_parser.py
tests/test_1doc.py
tests/test_3corpi.py

- typechecker: workflow output expressions can reference previous workflow outputs (#155)
- parser: task 'non-input' declarations can interleave anywhere among other sections (#156)
- parser: spike in newline at end of input (accommodates last-line comments)
- check: make UnusedDeclaration's heuristic index files exception case-insensitive

Add biowdl/tasks test corpus

---

WDL/Error.py
WDL/Expr.py
WDL/StdLib.py
WDL/Tree.py
test_corpi/contrived/scatter_collisions.wdl
tests/test_0eval.py

- OutOfBounds and EmptyArray inherit EvalError instead of ValidationError
- Expr.eval() reraises any error as EvalError
- introduce IntdeterminateType : ValidationError

refactoring errors

---

WDL/Type.py
WDL/Value.py
WDL/_parser.py
tests/test_3corpi.py
tests/test_4taskrun.py

An object literal typechecks with a struct type even if it omits some fields, if the omitted fields have optional types. At runtime, when the literal is coerced to the struct instance, these fields are filled in with null values. This should be done earlier during eval of the literal, in the future when there's a new struct literal syntax making the desired struct type known at eval time.

struct literals may omit optional fields

---

.pyre_configuration
WDL/CLI.py
WDL/Error.py
WDL/Expr.py
WDL/Lint.py
WDL/StdLib.py
WDL/Tree.py
WDL/Value.py
WDL/Walker.py
WDL/__init__.py
WDL/__main__.py
WDL/_parser.py
WDL/_util.py
WDL/runtime/error.py
WDL/runtime/task.py

Make all of the `WDL` package's internal imports relative.
Avoid abbreviating imported module names, to improve readability.

clean up internal imports

---

WDL/Expr.py
WDL/Lint.py
WDL/Tree.py
WDL/Walker.py

When a value or call output inside a workflow scatter or conditional section is referenced by some identifier expression outside of that section, there's an implied operation to gather the array of values/outputs (or conditional value). We add a little `Gather` AST node which may sit in `WDL.Expr.Ident.referee` to represent this operation abstractly, which will be useful in scheduling workflow execution.

explicate Gather operations in workflow dependencies

---

README.md
WDL/CLI.py
WDL/Error.py
WDL/Tree.py
WDL/Walker.py
tests/test_1doc.py
tests/test_2calls.py

- Introduces `WorkflowNode` as a base class for `Decl`, `Call`, `Scatter`, and `Conditional`. Each workflow node has a string ID (unique within the workflow) and reports the IDs of its dependencies.
- Furthermore `Scatter` and `Conditional` inherit `WorkflowSection : WorkflowNode` which centralizes access to the `Gather` nodes.
- Renames `{Workflow,Scatter,Conditional}.elements` to `.body`
The typechecker and cycle detection are unchanged, but probably can be simplified by using these new constructs (especially the gathers for typechecking).

refactoring workflow AST to facilitate runtime dependency analysis

---

WDL/CLI.py
WDL/Error.py
WDL/Lint.py
WDL/Tree.py
WDL/__init__.py
WDL/_parser.py
tests/test_3corpi.py

refactoring load() to allow caller to override file-reading logic

---

.gitignore
WDL/Expr.py
tests/test_0eval.py

I was working on a script to compile user documentation for WDL workflows and I found myself writing functions to render WDL expressions so the default values of inputs could be shown in these docs. It seemed to me that it might be be more appropriate to add these functions to the WDL bindings, hence this PR.
If this PR were to get merged, calling `str()` on most WDL.Expr classes would return a human-readable expression. The returned strings should look similar to how the expression would be written in WDL in most cases. For structs they currently would look like this, though: `(field: "A",  another_field: 1.1, yet_another_field: (another_struct: true))`.
Let me know what you think and if this is even something you're interested in. If so, could you point me to where I should add tests …

add __str__ to Expr classes

---

WDL/CLI.py
WDL/_util.py
WDL/runtime/task.py
stubs/docker/__init__.py
tests/test_4taskrun.py
tests/test_5stdlib.py
tests/test_6workflowrun.py

Switches the task runtime to schedule the docker container using swarm instead of the lower-level container API. Swarm is built into docker and includes useful resource scheduling logic (e.g. waiting until desired number of CPUs are "available") which we won't have to reinvent this way.

task runtime: switch to docker swarm for container scheduling

---

WDL/CLI.py
WDL/runtime/task.py
WDL/runtime/workflow.py
tests/test_4taskrun.py

cf. #210 
This implements the option to `run_local_task` but doesn't yet expose it through `run_local_workflow` or the CLI, to avoid creating merge conflicts with #229

task runtime: option to copy input files and mount them read/write

---

WDL/CLI.py
WDL/Lint.py
WDL/Tree.py
WDL/Walker.py
tests/test_3corpi.py

UnusedImport linter: detect use of imported struct typedefs

---

WDL/CLI.py
WDL/Value.py
WDL/_util.py
tests/test_6workflowrun.py

Task runtime's use of `copy.deepcopy` on values (`WDL.Value.Base`) led to excessive deep copying of portions of the AST, since value instances refer back to the `WDL.Expr.Base` that evaluated to them. This could lead to Python `RecursionError` (issue #239)
Exempts this reference from deep-copying. Also increases the Python call stack depth limit in the main entry point.

reduce call stack depth for large workflows

---

WDL/Expr.py
tests/test_0eval.py

The PR fixes #241 
The classes from StdLib which represent the functions don't always have the `name` attribute. As such `func.name` would throw an AttributeError.

fix bug which causes AttributeError when calling str for some functions

---

WDL/CLI.py
WDL/runtime/task.py
WDL/runtime/workflow.py
tests/runner.t
tests/test_4taskrun.py
tests/test_6workflowrun.py

Mount the input files under the container working directory, so that they're always in a directory to which the command has read/write access, even though the individual files are (by default) read-only. Then the task can create files alongside the index files and output them (e.g. samtools/tabix index files).
Mount all input files into one flat directory to the extent possible (barring filename collisions), also improving compatibility with index file handling assumptions.
Expose `copy_input_files` through `run_local_workflow` and CLI.

task runtime: revise input file mounting scheme

---

WDL/CLI.py
WDL/Error.py
WDL/Lint.py
WDL/Tree.py
WDL/Type.py
WDL/_parser.py
tests/test_1doc.py
tests/test_3corpi.py
tests/test_4taskrun.py
tests/test_5stdlib.py
tests/test_6workflowrun.py

These are always null at runtime; some existing workflows use this as a way of declaring a null value for later use.
Misc:
- Any coerces to/from optional types
- Update ENCODE ATAC-seq corpus
- Ensure {Task,Call,Workflow}.{available,required}_inputs iterate in source order
- Fix repetition in StaticTypeMismatch messages

allow unbound optional declarations outside of task/workflow inputs

---

WDL/runtime/task.py
WDL/runtime/workflow.py

Run tasks on a shared thread pool to enforce the requested limit on task concurrency.
Run sub-workflows on a second thread pool, so that they don't block threads meant for running tasks.

runner: share thread pool with sub-workflow calls

---

WDL/CLI.py
WDL/_util.py
WDL/runtime/task.py
WDL/runtime/workflow.py
tests/cromwell.t
tests/runner.t

Create the timestamp-named subdirectory whether the specified --dir exists or not, or append . to operate in --dir directly. Create all directories as needed.
Group the runner CLI arguments for tidiness.

runner: revise --dir behavior to be more predictable

---

WDL/CLI.py
WDL/runtime/download.py
WDL/runtime/error.py
WDL/runtime/task.py
WDL/runtime/workflow.py
stubs/docker/__init__.py
tests/runner.t
tests/test_4taskrun.py
tests/test_6workflowrun.py

File inputs for tasks and workflows can be URIs instead of a local filenames (including File values nested inside compound WDL values). Upon receiving this, the task runtime downloads the file somewhere under the run directory, and rewrites the original File values to the local filename before proceeding.
Downloads are performed by running synthetic WDL tasks using aria2c for http[s] and ftp. This bootstrapping will let us plug in all sorts of download tools (`aws s3`, `gsutil`, etc.) without having to add them as miniwdl installation dependencies.
Incidentally introduces `--as-me` option to run container commands as the invoking uid:gid.

download URI input files

---

Makefile
WDL/CLI.py
WDL/StdLib.py
WDL/_util.py
WDL/runtime/download.py
WDL/runtime/task.py
tests/getting_started.t
tests/test_4taskrun.py

If a docker image has been baked with a USER directive to drop privileges to some arbitrary uid (a good security practice), then it may have trouble accessing the mounted working directory, which is owned by the user who invoked miniwdl. To support this we
1. add the invoking user's group to the container (a feature of Docker)
2. ensure everything miniwdl provisions in the working directory has group read/write permission
Incidentally add a gs:// downloader and a test script mirroring the "Getting Started" tutorial, adding which provoked the permissions change.

add invoking user's group to docker containers

---

.travis.yml
Dockerfile
WDL/Tree.py
requirements.dev.txt
tests/test_4taskrun.py

It's useful to run the test suite as some arbitrary uid, because the runner works within numerous file permissions-related constraints.

run CI builds as non-root user

---

.travis.yml
Dockerfile
Makefile
WDL/_parser.py
tests/test_0eval.py

Save docker image layers with rarely-changing apt & PyPI package dependencies to a [public docker registry](https://quay.io/repository/mlin/miniwdl_ci?tab=tags), so that they can be reused by subsequent builds. This should be set up to automatically update everything whenever we bump or add package dependencies, but if needed we can evict the cache by deleting the 'latest' tag through the quay.io website.

speed up CI by caching docker layers

---

WDL/Lint.py

`miniwdl check` gives LOTS of warnings about the `disk` runtime attribute. I really dislike that both `disk` and `disks` exists, but for now that's what we are stuck with 🤷‍♂ .
Add valid keys to `Lint.py`, link documentation to TES.
As a sidenote, I did run `make check`, which reports many errors not related to this pull request. Not sure what to do with that, I configured my environment as instructed by `CONTRIBUTING.md`.

improvement(lint): consider TES runtime attributes

---

WDL/StdLib.py
requirements.txt
stubs/regex/__init__.py
tests/test_5stdlib.py

This PR implements openwdl/wdl#243
Uses the POSIX implementation of the regex package.

Use POSIX ERE for sub function

---

CONTRIBUTING.md
Makefile
WDL/CLI.py
WDL/_util.py
WDL/runtime/task.py
WDL/runtime/workflow.py
docs/getting_started.md
requirements.txt
stubs/docker/__init__.py
tests/test_4taskrun.py
tests/test_5stdlib.py
tests/test_6workflowrun.py
tests/test_7runner.py

- default `--runtime-cpu-max` and `--runtime-memory-max` to the resources available in Docker for Mac's virtual machine, rather than the entire host
- `miniwdl run_self_test` failure displays hint on overriding `TMPDIR` (#324)
- documentation
There are still some problems, particularly with the full test suite, tracking in #145

macOS compatibility improvements

---

WDL/StdLib.py
WDL/Value.py
tests/test_5stdlib.py

addresses #320 and adjusts other `read_{json,map}` type-coercion behavior to comply with spec

refine read_json() typechecking

---

WDL/runtime/config.py
WDL/runtime/config_templates/default.cfg
WDL/runtime/task.py
tests/test_4taskrun.py

The task runtime.memory is used as a scheduling reservation, but not enforced as a hard limit. Here we add config option [task_runtime] memory_limit_multiplier, which if positive causes a hard limit of memory_limit_multiplier*runtime.memory to be set. One can imagine scenarios where it could be useful to set this either above or below unity.

config option to set hard memory limit from task runtime.memory

---

WDL/CLI.py
WDL/Lint.py
test_corpi/contrived/contrived.wdl
tests/check.t
tests/test_3corpi.py

`miniwdl check` lint warnings can be suppressed by a comment containing `!WarningName` on the same line or the following line.
With `--strict`, it exits with nonzero status code if there are any shown lint warnings (in addition to syntax or type errors).

linter suppression comments & strict mode

---

WDL/runtime/error.py
WDL/runtime/task.py
tests/test_6workflowrun.py

Introduce concept of exogenous task "interruption" (e.g. spot/preemptible instance termination), with a separate retry budget controlled by `runtime.preemptible`. Refine interpretation of docker task states to recognize symptoms of interruption.

separate task retry logic for interruptions

---

WDL/runtime/task.py

Stress-testing revealed that a task whose assigned worker goes down can end up in one of three distinct modes:
1. state = running, exit code = -1
2. state = shutdown, orphaned, or remove
3. "desired state" = shutdown, orphaned, or remove (with non-terminal state)
The first case is common, while the last two are rare & appear only in stress-testing with artificially-induced worker shutdown :cry:

handle docker state corner case triggered by workers going down

---

.flake8
Makefile
WDL/CLI.py
WDL/Env.py
WDL/Error.py
WDL/Expr.py
WDL/Lint.py
WDL/Tree.py
WDL/Type.py
WDL/Value.py
WDL/__init__.py
WDL/_error_util.py
WDL/_parser.py
WDL/_util.py
WDL/runtime/__init__.py
WDL/runtime/cache.py
WDL/runtime/download.py
WDL/runtime/error.py
WDL/runtime/task.py
WDL/runtime/task_container.py
requirements.dev.txt

Enable flake8 linter

---

requirements.txt

See #412
Use `~=M.m` dependencies instead of `~=M.m.p` where possible. For `coloredlogs`, be even more permissive because this is a common library that is likely to cause dependency issues, and the newer major releases don't seem problematic.

Permissive dependencies

---

WDL/Expr.py
WDL/Tree.py
WDL/Value.py
WDL/_grammar.py
tests/test_0eval.py
tests/test_1doc.py
tests/test_5stdlib.py

- detect duplicate keys in map literals
- allow map literals with compound keys
- forbid use of compound-key maps in inputs/outputs (due to lack of JSON codec)

Map refinements

---

WDL/runtime/cache.py
docs/runner_reference.md

@MDunitz the feature has been working great in my local testing; just some light polishing here:
* made the cache get logic robust to errors that shouldn't happen, but we don't necessarily want miniwdl to crash if they do (e.g. the cache file is present but inaccessible or corrupt)
* polished log messages for concision and structure
* updated docs

call cache polishing

---

WDL/Expr.py
WDL/Tree.py
WDL/_grammar.py
WDL/_parser.py
WDL/runtime/workflow.py
tests/test_2calls.py
tests/test_7runner.py

Implements #113 https://github.com/openwdl/wdl/pull/297
New struct literal syntax similar to the old `object` syntax, but improves static typechecking by including the intended struct type name in the literal. So we can typecheck the members before later coercing them to a struct declaration/input. (The `object` syntax still works.)
Some detailed surgery to make declared struct types available to `Expr` typechecking logic, where before they'd only been needed in `Tree`.

WDL 2.0 struct literals

---

WDL/_grammar.py
WDL/_parser.py
tests/test_7runner.py

Very often multiple tasks share one or more inputs in common (e.g. `reference_genome_fasta` or `docker_image`) and we end up explicitly declaring a workflow input with the same name, then mechanically passing that in the call inputs for each applicable task. The product is numerous `foo=foo, bar=bar` entries in each call input. This change makes this pattern a bit more concise by allowing `foo=foo, bar=bar` to be abbreviated `foo, bar`.

abbreviated call input syntax

---

WDL/runtime/task_container.py
tests/test_4taskrun.py
tests/test_7runner.py

Tweaks allowing `make unit_tests` to pass on macOS (locally with Docker for Mac, which isn't available in CI)
The integration/CLI tests still need work

macOS unit test suite

---

WDL/runtime/cache.py
WDL/runtime/config.py
WDL/runtime/config_templates/default.cfg
WDL/runtime/task.py
WDL/runtime/workflow.py

CallCache pluggability

---

WDL/CLI.py
WDL/Env.py
WDL/Tree.py
WDL/__init__.py
WDL/_grammar.py
WDL/runtime/task.py
WDL/runtime/workflow.py
tests/runner.t
tests/test_7runner.py

Subset of #456 excluding 'hints' (which didn't make it into WDL 1.1)

[WDL 1.1] input overrides for task runtime values

---

WDL/runtime/error.py
WDL/runtime/task.py
WDL/runtime/task_container.py

- when task command fails, exception log reports stdout_file as well as stderr_file
- when task command succeeds, with nonempty stdout that isn't used in WDL outputs, note this in the log (and suggest `>&2`)

improve user-visibility of captured task stdout

---

WDL/CLI.py
WDL/Lint.py
WDL/Tree.py
WDL/__init__.py
WDL/runtime/task.py
WDL/runtime/workflow.py
tests/test_3corpi.py
tests/test_7runner.py

A call may supply None for an input with a non-optional type if it has a default expression, in which case the default will be used. In contrast, if the input has both a default expression and an optional type, None would be used. #505

Make inputs with defaults implicitly optional

---

WDL/CLI.py
WDL/runtime/config_templates/default.cfg
WDL/runtime/task.py
WDL/runtime/task_container.py
tests/runner.t
tests/test_7runner.py

@jgadling building on your much-appreciated #516, I extended it to work just like [`docker run --env`](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file):
* `--env X` to pass through environment variable `X`, skipping if `X` is undefined
* `--env X=foo` to set `X` outright
* supply `--env` multiple times with different variables
Let me know if you have any concerns with this variation on it!
While hacking on this, I remembered how miniwdl [passes AWS credentials to its internal S3 downloader](https://github.com/chanzuckerberg/miniwdl/blob/6963147e3324ef738f899d6f78ab914e2d3bbd06/WDL/runtime/download.py#L308-L332): it *generates a temporary script file* defining the necessary environment variables, then [sources that …

add --env & config option to set values in all task environments

---

WDL/StdLib.py
WDL/Type.py
WDL/Value.py
tests/test_0eval.py
tests/test_4taskrun.py
tests/test_5stdlib.py

Initializing a struct from unsafe `read_json()`, change the transient intermediate codepath to go through `Object` instead of `Map`, avoiding various problems caused by spurious attempt to unify heterogeneous value types. Improve error messages.
mostly addresses #524

rework struct initialization from read_json()

---

WDL/CLI.py

Tried to use `print_error()` from a typechecked codebase
```
wdl2cwl/main.py:43:9: error: Call to untyped function "print_error" in typed context  [no-untyped-call]
WDL.CLI.print_error(exn)
```

add type hints for print_error()

---

WDL/_parser.py
tests/test_1doc.py

Closes #548 
Clearing the comments cache before running the parser. An alternative could be to wrap the parser call in a try/except, and clear the buffer there. Happy to amend it, or if anyone would like, feel free to edit/squash the commits here :+1: 
Took a little longer than expected to remember how to run a single `unittest` test :grimacing: , so note for future self (as I'll forget again): `python setup.py test -s tests.test_1doc.TestDoc.test_issue548_comments_buffer`

Fix parser comments cache

---

WDL/runtime/backend/docker_swarm.py
WDL/runtime/config_templates/default.cfg
WDL/runtime/task.py
docs/runner_reference.md
tests/test_7runner.py

We increasingly rely on miniwdl in our batch processing pipelines, and we're currently trying to improve the developer experience for engineers who work on those pipelines. Our local development environments make use of `docker-compose` and docker networks to make the interactions between our microservices resemble our production environment. Since miniwdl doesn't currently have support for docker networks, the tasks it runs don't have access to the services in our local dev environment and can't interact with our local S3 service, database, etc.
This is a pretty straightforward addition of a `docker_network` runtime config flag.

Add support for attaching tasks to docker networks.

---

WDL/Zip.py
tests/test_3corpi.py

See #556 . I think it is best to make reproducible zip/tar packages by default. It should be part of the SPEC.  
Since zip and tar packages store files in a certain order, files are sorted by their path in the archive and added in that order. This ensures the order for a given set of files is always the same. 
Since compression can change with different libraries files are stored uncompressed. 
Since modification times can ruin your day for reproducibility, the modification time is set to 0 for tarfiles and to 1980-1-1 00:00 for zipfiles. These are both the lowest possible timestamps.

Always create reproducible zips and tars

---

WDL/runtime/config.py
WDL/runtime/download.py
tests/test_7runner.py

`Directory` URIs for the `gs://` scheme have not been implemented, though the scheme is available for `s3://` URIs.
The command change to allow `gsutil` to download a directory rather than a single file is to add the `-r` flag. To implement this, there is now an additional download task plugin, and a second gsutil function for directory rather than file download.
Testing was added based on the `s3:` test that fetches a 1000genomes structural variants directory. The GCS mirror of the same repo has four files rather than two, so the asserts on file counts were updated.
I needed this for compatibility with a local cromwell install, and it has worked so far in pipeline development.

add gsutil directory downloader

---

WDL/runtime/backend/cli_subprocess.py
WDL/runtime/backend/singularity.py
WDL/runtime/config_templates/default.cfg
tests/singularity.t

This is required for supporting miniwdl-slurm and other HPC plugins. When submitting to a HPC there is usually a shared filesystem. The submit node and the worker nodes can access this filesystem. 
The singularity cache cannot and should not be shared between nodes because there may be conflicts. The image should be created by singularity on the submit node, then after that the worker nodes can use this image. The location of the singularity images dir needs to be configurable in order to put it on the shared filesystem.
The same holds true for the temp dir.
A configuration parameter has been added under the "[singularity]" section called "image_cache". By default this is turned off. (The miniwdl-slurm plugin will override this default by setting it to some directory in the current …

Singularity cache

---

WDL/Value.py
WDL/runtime/task.py
tests/test_7runner.py

Replace a hack that caused problems (#614) with optional File/Directory outputs, related to when & how a nonexistent output path is changed to `None`.

improve File? task output processing

---

WDL/Tree.py
WDL/_grammar.py
WDL/_parser.py
WDL/runtime/task.py
tests/test_7runner.py

Prototypes making task declarations populate container environment variables by prefixing the declaration with the `env` keyword
under discussion in https://github.com/openwdl/wdl/pull/504
alternative to #503

task env declarations

---

docs/wdlviz.md

Documentation for wdlviz lists wrong conda package. This is a quick update so that conda users install `python-graphviz` (correct), not `graphviz` (incorrect).
Just substituted the correct package name for the incorrect one.
Honestly, I haven't completed any of the checklist items. But, because this is just a quick update to the documentation and only consists of adding a few letters, I doubt all of these are necessary. If you need me to complete any of these extra steps though, let me know. Thanks!

correct graphviz conda package

---

WDL/CLI.py
WDL/Zip.py
tests/test_3corpi.py

...
#640 
Simply add the flag :wink:. 
There is also one bug fix about an invalid cross-device link that gets triggered because I have my `/home` dir on a separate partition. So `/tmp` and `/home` are on different devices and this triggers an invalid cross-device link warning when os.rename is used. I use the higher level shutil.move instead. This bug fix is in a single commit that can be cherry picked. 
I have not added tests yet because you might have different ideas about how to implement this. I think a "--license" flag to include a license file that also gets added to the manifest would be quite a neat feature for redistributable WDL packages.

Additional files can be zipped in with miniwdl zip. Fix for cross-device link error.

---

WDL/_util.py

This should fix #665.
I made the `@export` annotation function generic so it returns the same type as its input.
**Does not work**, `pyre-check==0.0.27` is required according to `requirements-dev.txt`, which is not available for any Python newer than 3.6, which ended security support on 23 Dec 2021. Current `pyre-check` versions do not have the `--show-parse-errors` option used in the script.

Make export function preserve types

---

examples/plugin_log_task_usage/StressTest.wdl
examples/plugin_log_task_usage/miniwdl_log_task_usage.py
examples/plugin_log_task_usage/setup.py

Work with both cgroup v1 and v2
Worked on tracking disk I/O as well, but backed out after finding that the cgroup I/O counters don't include network filesystems, which would be a major use case. To be revisited later, commit history preserved herein.

Modernize task CPU/memory usage example plugin

---

WDL/Lint.py
WDL/Type.py
test_corpi/contrived/issue669.wdl
tests/test_3corpi.py

Issue #669
Types `File` & `String` to unify to `String`, not `File`; similarly for `Directory`.
Adjust related linter warnings.

adjust File/Directory-to-String type coercions

---

WDL/runtime/task.py

Address the failure in https://github.com/chanzuckerberg/miniwdl/issues/726 by checking for falsy `Map` values in the same way the branch above does for `Array`s.
Just mirroring the handling of empty Arrays!

check for falsy mappings

---

WDL/Expr.py
WDL/_parser.py
WDL/runtime/config_templates/default.cfg
WDL/runtime/task.py
tests/test_4taskrun.py

Unifies dedent logic with multi-line strings.
Introduces `WDL.Expr.TaskCommand`, a specialization of `WDL.Expr.String` that handles this and other command-specific evaluation logic.
Config option `[task_runtime] old_command_dedent` to restore old post-eval dedenting, just in case someone needs.
see: #674

dedent task commands before eval/interpolation

---

WDL/Error.py
WDL/Expr.py
WDL/_parser.py

Introduce `WDL.Expr.MultiLineString` which hosts most of the specialized evaluation logic that had been in the parser. (Follow-up to #734)

refactor multi-line string implementation
